import mongoose from 'mongoose';
import dotenv from 'dotenv';
import User from './models/User';
import Lead from './models/Lead';
import Call from './models/Call';
import Notification from './models/Notification';

import { env } from './config/env';

const MONGODB_URI = env.MONGODB_URI || 'mongodb://localhost:27017/insurelead';

const today = new Date();
const ago = (days: number) => new Date(today.getTime() - days * 86400000);
const future = (days: number) => new Date(today.getTime() + days * 86400000);

async function seed() {
  await mongoose.connect(MONGODB_URI, {
    serverSelectionTimeoutMS: 60000,
    family: 4, // Force IPv4
  });
  console.log('Connected to MongoDB');

  // Clear existing data
  await User.deleteMany({});
  await Lead.deleteMany({});
  await Call.deleteMany({});
  await Notification.deleteMany({});
  console.log('Cleared existing data');

  // --- Users ---
  const users = await User.create([
    { name: 'Chiren', email: 'chiren@ualliances.com', password: 'chiren@1100', avatar: 'CH', role: 'admin', leadsAssigned: 45, callsMade: 128, followUpsCompleted: 34, followUpsPending: 8, conversionRate: 24, revenueClosed: 128500 },
    { name: 'Rajesh Patel', email: 'rajesh@ualliances.com', password: 'Team2026!rp', avatar: 'RP', role: 'sdr', leadsAssigned: 38, callsMade: 96, followUpsCompleted: 28, followUpsPending: 12, conversionRate: 18, revenueClosed: 87200 },
    { name: 'Priya Sharma', email: 'priya@ualliances.com', password: 'Team2026!ps', avatar: 'PS', role: 'sdr', leadsAssigned: 52, callsMade: 145, followUpsCompleted: 41, followUpsPending: 5, conversionRate: 28, revenueClosed: 156800 },
    { name: 'Amit Desai', email: 'amit@ualliances.com', password: 'Team2026!ad', avatar: 'AD', role: 'sdr', leadsAssigned: 31, callsMade: 72, followUpsCompleted: 19, followUpsPending: 15, conversionRate: 15, revenueClosed: 54300 },
    { name: 'Deepa Joshi', email: 'deepa@ualliances.com', password: 'Team2026!dj', avatar: 'DJ', role: 'hr', leadsAssigned: 0, callsMade: 0, followUpsCompleted: 0, followUpsPending: 0, conversionRate: 0, revenueClosed: 0 },
    { name: 'Karan Shah', email: 'karan@ualliances.com', password: 'Team2026!ks', avatar: 'KS', role: 'leadgen', leadsAssigned: 0, callsMade: 0, followUpsCompleted: 0, followUpsPending: 0, conversionRate: 0, revenueClosed: 0 },
  ]);
  console.log(`Created ${users.length} users`);

  // --- Leads ---
  const leads = await Lead.create([
    { date: ago(5), source: 'LinkedIn', name: 'Ravi Mehta', title: 'VP of Operations', companyName: 'Navrang Exports', email: 'ravi@navrang.com', workDirectPhone: '+91 98980 12345', mobilePhone: '+91 98250 99999', homePhone: '', corporatePhone: '+91 79 2640 0000', otherPhone: '', companyPhone: '+91 79 2640 0001', employeeCount: 250, personLinkedinUrl: 'https://linkedin.com/in/ravimehta', website: 'https://navrangexports.com', companyLinkedinUrl: 'https://linkedin.com/company/navrang', city: 'Ahmedabad', state: 'Gujarat', status: 'New Lead', assignedAgent: 'Chiren', addedBy: 'Chiren', nextFollowUp: future(1), callCount: 0, lastActivity: ago(0), notes: 'Interested in business coverage', priority: 'A', segment: 'Insurance', sourceChannel: 'Cold – High Fit', qualityGatePass: true, qualification: { rightPerson: false, realNeed: false, timing: false, qualifiedAt: null, qualifiedBy: '' }, cadence: { type: 'cold-14day', startedAt: ago(5), currentDay: 5, touches: [{ day: 1, type: 'call', completed: true, completedAt: ago(5) }, { day: 1, type: 'email', completed: true, completedAt: ago(5) }, { day: 2, type: 'call', completed: true, completedAt: ago(4) }, { day: 2, type: 'linkedin', completed: true, completedAt: ago(4) }, { day: 4, type: 'call', completed: false }] }, stageHistory: [{ stage: 'New Lead', enteredAt: ago(5) }], activities: [{ type: 'note', description: 'Lead imported via CSV', timestamp: ago(0), agent: 'Chiren' }] },
    { date: ago(10), source: 'CSV Import', name: 'Aarti Pandya', title: 'HR Director', companyName: 'Symphony Tech', email: 'aarti@symphonytech.in', workDirectPhone: '+91 94260 56789', mobilePhone: '+91 94280 99999', homePhone: '+91 79 2656 1111', corporatePhone: '', otherPhone: '', companyPhone: '+91 79 2656 0000', employeeCount: 85, personLinkedinUrl: 'https://linkedin.com/in/aartipandya', website: 'https://symphonytech.in', companyLinkedinUrl: 'https://linkedin.com/company/symphonytech', city: 'Ahmedabad', state: 'Gujarat', status: 'Working', assignedAgent: 'Rajesh Patel', addedBy: 'Rajesh Patel', nextFollowUp: ago(1), callCount: 2, lastActivity: ago(1), notes: 'Bolya ke kal call karna, interested in bundle', priority: 'B', segment: 'Insurance', sourceChannel: 'Cold – Bulk Data', qualityGatePass: true, qualification: { rightPerson: true, realNeed: false, timing: false, qualifiedAt: null, qualifiedBy: '' }, cadence: { type: 'cold-14day', startedAt: ago(10), currentDay: 10, touches: [{ day: 1, type: 'call', completed: true, completedAt: ago(10) }, { day: 1, type: 'email', completed: true, completedAt: ago(10) }, { day: 2, type: 'call', completed: true, completedAt: ago(9) }, { day: 2, type: 'linkedin', completed: true, completedAt: ago(9) }, { day: 4, type: 'call', completed: true, completedAt: ago(6) }, { day: 4, type: 'email', completed: true, completedAt: ago(6) }, { day: 6, type: 'call', completed: true, completedAt: ago(4) }, { day: 8, type: 'email', completed: true, completedAt: ago(2) }, { day: 10, type: 'call', completed: false }] }, stageHistory: [{ stage: 'New Lead', enteredAt: ago(10) }, { stage: 'Working', enteredAt: ago(8) }], activities: [{ type: 'call', description: 'Initial call - interested', timestamp: ago(2), agent: 'Rajesh Patel' }, { type: 'call', description: 'Follow-up call - requested quote. Bhai ne detail maangi chhe.', timestamp: ago(1), agent: 'Rajesh Patel' }] },
    { date: ago(15), source: 'LinkedIn', name: 'Vikram Thakur', title: 'CEO', companyName: 'Thakur & Sons Logistics', email: 'vikram@thakurlogistics.com', workDirectPhone: '+91 99988 67890', mobilePhone: '+91 98240 99999', homePhone: '', corporatePhone: '+91 79 2642 0000', otherPhone: '', companyPhone: '+91 79 2642 0001', employeeCount: 42, personLinkedinUrl: 'https://linkedin.com/in/vikramthakur', website: 'https://thakurlogistics.com', companyLinkedinUrl: 'https://linkedin.com/company/thakurlogistics', city: 'Gandhinagar', state: 'Gujarat', status: 'Connected', assignedAgent: 'Priya Sharma', addedBy: 'Chiren', nextFollowUp: ago(3), callCount: 4, lastActivity: ago(2), notes: 'Comparing with competitor. Unka MD bola thoda time do.', priority: 'A', segment: 'Insurance', sourceChannel: 'Warm – Engaged', qualityGatePass: true, qualification: { rightPerson: true, realNeed: true, timing: false, qualifiedAt: null, qualifiedBy: '' }, cadence: { type: 'warm-fast', startedAt: ago(15), currentDay: 15, touches: [{ day: 0, type: 'call', completed: true }, { day: 0, type: 'email', completed: true }, { day: 1, type: 'call', completed: true }, { day: 1, type: 'linkedin', completed: true }, { day: 2, type: 'call', completed: true }, { day: 3, type: 'email', completed: true }] }, stageHistory: [{ stage: 'New Lead', enteredAt: ago(15) }, { stage: 'Working', enteredAt: ago(12) }, { stage: 'Connected', enteredAt: ago(8) }], activities: [{ type: 'call', description: 'Discussed policy options', timestamp: ago(5), agent: 'Priya Sharma' }, { type: 'follow-up', description: 'Scheduled follow-up', timestamp: ago(3), agent: 'Priya Sharma' }] },
    { date: ago(30), source: 'Referral', name: 'Kajal Patel', title: 'CFO', companyName: 'Kajal Financials', email: 'kajal@kajalfin.in', workDirectPhone: '+91 90999 78901', mobilePhone: '', homePhone: '+91 79 2658 1111', corporatePhone: '', otherPhone: '', companyPhone: '+91 79 2658 0000', employeeCount: 120, personLinkedinUrl: 'https://linkedin.com/in/kajalpatel', website: 'https://kajalfin.in', companyLinkedinUrl: 'https://linkedin.com/company/kajalfin', city: 'Ahmedabad', state: 'Gujarat', status: 'Closed Won', assignedAgent: 'Chiren', addedBy: 'Priya Sharma', closedBy: 'Chiren', closedAt: ago(1), closedReason: 'Signed policy', nextFollowUp: null, callCount: 6, lastActivity: ago(1), notes: 'Full deal done. Diwali pe sweets bhejna hai.', revenue: 245000, priority: 'A', segment: 'Finance', sourceChannel: 'Referral', qualityGatePass: true, qualification: { rightPerson: true, realNeed: true, timing: true, qualifiedAt: ago(18), qualifiedBy: 'Chiren' }, stageHistory: [{ stage: 'New Lead', enteredAt: ago(30) }, { stage: 'Working', enteredAt: ago(25) }, { stage: 'Qualified', enteredAt: ago(18) }, { stage: 'Meeting Booked', enteredAt: ago(12) }, { stage: 'Meeting Completed', enteredAt: ago(8) }, { stage: 'Proposal Sent', enteredAt: ago(5) }, { stage: 'Closed Won', enteredAt: ago(1) }], activities: [{ type: 'status-change', description: 'Status changed to Closed Won', timestamp: ago(1), agent: 'Chiren' }] },
    { date: ago(7), source: 'Website', name: 'Neha Gupta', title: 'Owner', companyName: 'Gupta Auto Services', email: 'neha@guptaauto.in', workDirectPhone: '+91 93270 89012', mobilePhone: '+91 98255 99999', homePhone: '', corporatePhone: '', otherPhone: '+91 79 2685 2222', companyPhone: '+91 79 2685 0000', employeeCount: 18, personLinkedinUrl: '', website: 'https://guptaauto.in', companyLinkedinUrl: '', city: 'Ahmedabad', state: 'Gujarat', status: 'Connected', assignedAgent: 'Amit Desai', addedBy: 'Amit Desai', nextFollowUp: future(2), callCount: 1, lastActivity: ago(3), notes: 'Need to align meeting next week. Sir ne bola call back karna.', priority: 'B', segment: 'Healthcare', sourceChannel: 'Manual', qualityGatePass: true, qualification: { rightPerson: true, realNeed: false, timing: false, qualifiedAt: null, qualifiedBy: '' }, cadence: { type: 'cold-14day', startedAt: ago(7), currentDay: 7, touches: [{ day: 1, type: 'call', completed: true }, { day: 1, type: 'email', completed: true }, { day: 2, type: 'call', completed: true }, { day: 2, type: 'linkedin', completed: true }, { day: 4, type: 'call', completed: true }, { day: 4, type: 'email', completed: true }, { day: 6, type: 'call', completed: false }] }, stageHistory: [{ stage: 'New Lead', enteredAt: ago(7) }, { stage: 'Working', enteredAt: ago(5) }, { stage: 'Connected', enteredAt: ago(3) }], activities: [{ type: 'call', description: 'First contact call', timestamp: ago(3), agent: 'Amit Desai' }] },
    { date: ago(20), source: 'Referral', name: 'Manoj Trivedi', title: 'Marketing Manager', companyName: 'Trivedi Media Group', email: 'manoj@trivedimedia.com', workDirectPhone: '+91 97250 90123', mobilePhone: '', homePhone: '+91 79 2646 1111', corporatePhone: '+91 79 2646 0000', otherPhone: '', companyPhone: '+91 79 2646 0001', employeeCount: 65, personLinkedinUrl: 'https://linkedin.com/in/manojtrivedi', website: 'https://trivedimedia.com', companyLinkedinUrl: 'https://linkedin.com/company/trivedimedia', city: 'Ahmedabad', state: 'Gujarat', status: 'Closed Lost', assignedAgent: 'Rajesh Patel', addedBy: 'Rajesh Patel', closedReason: 'Went with competitor', nextFollowUp: null, callCount: 3, lastActivity: ago(7), notes: 'Sasta rate doondh rahe the. Competitor ke paas gaye.', priority: 'B', segment: 'Other', sourceChannel: 'Referral', qualityGatePass: true, qualification: { rightPerson: false, realNeed: true, timing: false, qualifiedAt: null, qualifiedBy: '' }, stageHistory: [{ stage: 'New Lead', enteredAt: ago(20) }, { stage: 'Working', enteredAt: ago(16) }, { stage: 'Connected', enteredAt: ago(12) }, { stage: 'Closed Lost', enteredAt: ago(7) }], activities: [{ type: 'status-change', description: 'Status changed to Closed Lost', timestamp: ago(7), agent: 'Rajesh Patel' }] },
    { date: ago(1), source: 'Manual', name: 'Hardik Parikh', title: 'CTO', companyName: 'Parikh Solutions', email: 'hardik@parikhsol.in', workDirectPhone: '+91 99250 01234', mobilePhone: '+91 90990 99999', homePhone: '', corporatePhone: '+91 79 2676 0000', otherPhone: '', companyPhone: '+91 79 2676 0001', employeeCount: 310, personLinkedinUrl: 'https://linkedin.com/in/hardikparikh', website: 'https://parikhsol.in', companyLinkedinUrl: 'https://linkedin.com/company/parikhsol', city: 'Surat', state: 'Gujarat', status: 'New Lead', assignedAgent: 'Priya Sharma', addedBy: 'Priya Sharma', nextFollowUp: future(0), callCount: 0, lastActivity: ago(0), notes: 'Looking for a solid corporate policy.', priority: 'C', segment: '', sourceChannel: 'Manual', qualityGatePass: false, qualification: { rightPerson: false, realNeed: false, timing: false, qualifiedAt: null, qualifiedBy: '' }, stageHistory: [{ stage: 'New Lead', enteredAt: ago(1) }], activities: [{ type: 'note', description: 'Lead imported via CSV', timestamp: ago(0), agent: 'Priya Sharma' }] },
    { date: ago(8), source: 'CSV Import', name: 'Seema Shah', title: 'Office Manager', companyName: 'Shah & Partners', email: 'seema@shahpartners.in', workDirectPhone: '+91 94288 12345', mobilePhone: '', homePhone: '+91 79 2630 1111', corporatePhone: '', otherPhone: '', companyPhone: '+91 79 2630 0000', employeeCount: 12, personLinkedinUrl: 'https://linkedin.com/in/seemashah', website: 'https://shahpartners.in', companyLinkedinUrl: '', city: 'Rajkot', state: 'Gujarat', status: 'Working', assignedAgent: 'Chiren', addedBy: 'Chiren', nextFollowUp: ago(2), callCount: 1, lastActivity: ago(2), notes: 'Phone uthaya na tha. Subah try karna padega.', priority: 'C', segment: 'Insurance', sourceChannel: 'Cold – Bulk Data', qualityGatePass: true, qualification: { rightPerson: false, realNeed: false, timing: false, qualifiedAt: null, qualifiedBy: '' }, stageHistory: [{ stage: 'New Lead', enteredAt: ago(8) }, { stage: 'Working', enteredAt: ago(6) }], activities: [{ type: 'call', description: 'Intro call completed', timestamp: ago(2), agent: 'Chiren' }] },
    { date: ago(12), source: 'Website', name: 'Chetan Prajapati', title: 'President', companyName: 'Prajapati Textiles', email: 'chetan@prajapatitextiles.com', workDirectPhone: '+91 98254 23456', mobilePhone: '+91 98790 99999', homePhone: '', corporatePhone: '+91 79 2532 0000', otherPhone: '', companyPhone: '+91 79 2532 0001', employeeCount: 95, personLinkedinUrl: 'https://linkedin.com/in/chetanprajapati', website: 'https://prajapatitextiles.com', companyLinkedinUrl: 'https://linkedin.com/company/prajapatitextiles', city: 'Ahmedabad', state: 'Gujarat', status: 'Connected', assignedAgent: 'Amit Desai', addedBy: 'Priya Sharma', nextFollowUp: ago(5), callCount: 2, lastActivity: ago(4), notes: 'Next meeting fix karni hai. Chetan bhai interest dikha rahe hain.', priority: 'A', segment: 'Healthcare', sourceChannel: 'Cold – High Fit', qualityGatePass: true, qualification: { rightPerson: true, realNeed: true, timing: true, qualifiedAt: ago(7), qualifiedBy: 'Amit Desai' }, stageHistory: [{ stage: 'New Lead', enteredAt: ago(12) }, { stage: 'Working', enteredAt: ago(10) }, { stage: 'Connected', enteredAt: ago(7) }], activities: [{ type: 'follow-up', description: 'Follow-up scheduled', timestamp: ago(5), agent: 'Amit Desai' }] },
    { date: ago(3), source: 'LinkedIn', name: 'Jignesh Makwana', title: 'Director of Sales', companyName: 'Makwana Enterprises', email: 'jignesh@makwana.in', workDirectPhone: '+91 98795 34567', mobilePhone: '+91 99099 99999', homePhone: '', corporatePhone: '', otherPhone: '', companyPhone: '+91 79 2546 0000', employeeCount: 150, personLinkedinUrl: 'https://linkedin.com/in/jigneshmakwana', website: 'https://makwana.in', companyLinkedinUrl: 'https://linkedin.com/company/makwana', city: 'Vadodara', state: 'Gujarat', status: 'Working', assignedAgent: 'Priya Sharma', addedBy: 'Rajesh Patel', nextFollowUp: future(3), callCount: 1, lastActivity: ago(1), notes: 'Sir was busy. Said call back afternoon me karna.', priority: 'B', segment: 'Insurance', sourceChannel: 'LinkedIn', qualityGatePass: true, qualification: { rightPerson: false, realNeed: true, timing: false, qualifiedAt: null, qualifiedBy: '' }, stageHistory: [{ stage: 'New Lead', enteredAt: ago(3) }, { stage: 'Working', enteredAt: ago(1) }], activities: [{ type: 'call', description: 'Initial contact', timestamp: ago(1), agent: 'Priya Sharma' }] },
  ]);
  console.log(`Created ${leads.length} leads`);

  // --- Calls ---
  const leadMap: Record<string, string> = {};
  leads.forEach(l => { leadMap[l.name] = l._id.toString(); });

  const calls = await Call.create([
    { leadId: leadMap['Aarti Pandya'], leadName: 'Aarti Pandya', agentName: 'Rajesh Patel', date: ago(1), time: '10:30 AM', duration: '6 min', status: 'Completed', notes: 'Follow-up call - bhai boli quote bhej do.', hasRecording: true },
    { leadId: leadMap['Aarti Pandya'], leadName: 'Aarti Pandya', agentName: 'Rajesh Patel', date: ago(2), time: '2:15 PM', duration: '4 min', status: 'Completed', notes: 'Initial call - acha response tha', hasRecording: true },
    { leadId: leadMap['Vikram Thakur'], leadName: 'Vikram Thakur', agentName: 'Priya Sharma', date: ago(5), time: '11:00 AM', duration: '8 min', status: 'Completed', notes: 'Discussed policy options, next week meeting karwao', hasRecording: false },
    { leadId: leadMap['Neha Gupta'], leadName: 'Neha Gupta', agentName: 'Amit Desai', date: ago(3), time: '9:45 AM', duration: '3 min', status: 'Follow-up', notes: 'First contact call aayo', hasRecording: true },
    { leadId: leadMap['Seema Shah'], leadName: 'Seema Shah', agentName: 'Chiren', date: ago(2), time: '3:00 PM', duration: '5 min', status: 'Completed', notes: 'Intro done. Need to align next week call.', hasRecording: false },
    { leadId: leadMap['Jignesh Makwana'], leadName: 'Jignesh Makwana', agentName: 'Priya Sharma', date: ago(1), time: '1:20 PM', duration: '7 min', status: 'Completed', notes: 'Initial contact with Jignesh bhai', hasRecording: true },
    { leadId: leadMap['Vikram Thakur'], leadName: 'Vikram Thakur', agentName: 'Priya Sharma', date: ago(7), time: '4:00 PM', duration: '0 min', status: 'Missed', notes: 'Phone nahi uthaya', hasRecording: false },
    { leadId: leadMap['Manoj Trivedi'], leadName: 'Manoj Trivedi', agentName: 'Rajesh Patel', date: ago(8), time: '10:00 AM', duration: '12 min', status: 'Completed', notes: 'Extended discussion about coverage and rate', hasRecording: true },
    { leadId: leadMap['Kajal Patel'], leadName: 'Kajal Patel', agentName: 'Chiren', date: ago(3), time: '11:30 AM', duration: '15 min', status: 'Completed', notes: 'Closing call - payment received', hasRecording: true },
    { leadId: leadMap['Chetan Prajapati'], leadName: 'Chetan Prajapati', agentName: 'Amit Desai', date: ago(4), time: '2:00 PM', duration: '4 min', status: 'Follow-up', notes: 'Needs more info on family plans', hasRecording: false },
    { leadId: leadMap['Ravi Mehta'], leadName: 'Ravi Mehta', agentName: 'Chiren', date: ago(0), time: '9:00 AM', duration: '2 min', status: 'Missed', notes: 'Busy the, baad me call karna hai', hasRecording: false },
    { leadId: leadMap['Hardik Parikh'], leadName: 'Hardik Parikh', agentName: 'Priya Sharma', date: ago(0), time: '10:15 AM', duration: '6 min', status: 'Completed', notes: 'Corporate inquiry - send proposal soon', hasRecording: true },
  ]);
  console.log(`Created ${calls.length} calls`);

  // --- Notifications ---
  const notifications = await Notification.create([
    { type: 'overdue', title: 'Overdue Follow-up', message: 'Follow-up with Vikram Thakur is 3 days overdue', timestamp: ago(0), read: false, leadId: leadMap['Vikram Thakur'] },
    { type: 'overdue', title: 'Overdue Follow-up', message: 'Follow-up with Chetan Prajapati is 5 days overdue', timestamp: ago(0), read: false, leadId: leadMap['Chetan Prajapati'] },
    { type: 'follow-up', title: 'Follow-up Today', message: 'Follow-up with Hardik Parikh is due today', timestamp: ago(0), read: false, leadId: leadMap['Hardik Parikh'] },
    { type: 'overdue', title: 'Overdue Follow-up', message: 'Follow-up with Aarti Pandya is 1 day overdue', timestamp: ago(0), read: false, leadId: leadMap['Aarti Pandya'] },
    { type: 'assignment', title: 'New Lead Assigned', message: 'Ravi Mehta has been assigned to you', timestamp: ago(0), read: true },
    { type: 'system', title: 'CSV Import Complete', message: '15 leads imported successfully', timestamp: ago(1), read: true },
  ]);
  console.log(`Created ${notifications.length} notifications`);

  console.log('\n✅ Database seeded successfully!');

  await mongoose.disconnect();
  process.exit(0);
}

seed().catch((err) => {
  console.error('Seed error:', err);
  process.exit(1);
});
